/*
 * Payments API inbound
 * The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@peachpayments.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckoutOptions
 */
public class CheckoutOptionsTest {
    private final CheckoutOptions model = new CheckoutOptions();

    /**
     * Model tests for CheckoutOptions
     */
    @Test
    public void testCheckoutOptions() {
        // TODO: test CheckoutOptions
    }

    /**
     * Test the property 'defaultPaymentMethod'
     */
    @Test
    public void defaultPaymentMethodTest() {
        // TODO: test defaultPaymentMethod
    }

    /**
     * Test the property 'forceDefaultMethod'
     */
    @Test
    public void forceDefaultMethodTest() {
        // TODO: test forceDefaultMethod
    }

    /**
     * Test the property 'tokeniseCard'
     */
    @Test
    public void tokeniseCardTest() {
        // TODO: test tokeniseCard
    }

}
