/*
 * Payments API inbound
 * The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@peachpayments.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckoutState
 */
public class CheckoutStateTest {
    private final CheckoutState model = new CheckoutState();

    /**
     * Model tests for CheckoutState
     */
    @Test
    public void testCheckoutState() {
        // TODO: test CheckoutState
    }

    /**
     * Test the property 'defaultPaymentMethod'
     */
    @Test
    public void defaultPaymentMethodTest() {
        // TODO: test defaultPaymentMethod
    }

    /**
     * Test the property 'forceDefaultMethod'
     */
    @Test
    public void forceDefaultMethodTest() {
        // TODO: test forceDefaultMethod
    }

    /**
     * Test the property 'tokeniseCard'
     */
    @Test
    public void tokeniseCardTest() {
        // TODO: test tokeniseCard
    }

    /**
     * Test the property 'registrationId'
     */
    @Test
    public void registrationIdTest() {
        // TODO: test registrationId
    }

    /**
     * Test the property 'checkoutId'
     */
    @Test
    public void checkoutIdTest() {
        // TODO: test checkoutId
    }

    /**
     * Test the property 'transactionUniqueId'
     */
    @Test
    public void transactionUniqueIdTest() {
        // TODO: test transactionUniqueId
    }

    /**
     * Test the property 'resultCode'
     */
    @Test
    public void resultCodeTest() {
        // TODO: test resultCode
    }

    /**
     * Test the property 'paymentBrand'
     */
    @Test
    public void paymentBrandTest() {
        // TODO: test paymentBrand
    }

}
