/*
 * Payments API inbound
 * The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@peachpayments.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckoutSuccessfulWebhookAllOf
 */
public class CheckoutSuccessfulWebhookAllOfTest {
    private final CheckoutSuccessfulWebhookAllOf model = new CheckoutSuccessfulWebhookAllOf();

    /**
     * Model tests for CheckoutSuccessfulWebhookAllOf
     */
    @Test
    public void testCheckoutSuccessfulWebhookAllOf() {
        // TODO: test CheckoutSuccessfulWebhookAllOf
    }

    /**
     * Test the property 'merchantName'
     */
    @Test
    public void merchantNameTest() {
        // TODO: test merchantName
    }

    /**
     * Test the property 'reconAuthCode'
     */
    @Test
    public void reconAuthCodeTest() {
        // TODO: test reconAuthCode
    }

    /**
     * Test the property 'reconResultCode'
     */
    @Test
    public void reconResultCodeTest() {
        // TODO: test reconResultCode
    }

    /**
     * Test the property 'reconRrn'
     */
    @Test
    public void reconRrnTest() {
        // TODO: test reconRrn
    }

    /**
     * Test the property 'resultCode'
     */
    @Test
    public void resultCodeTest() {
        // TODO: test resultCode
    }

    /**
     * Test the property 'resultDescription'
     */
    @Test
    public void resultDescriptionTest() {
        // TODO: test resultDescription
    }

    /**
     * Test the property 'resultDetailsAcquirerResponse'
     */
    @Test
    public void resultDetailsAcquirerResponseTest() {
        // TODO: test resultDetailsAcquirerResponse
    }

    /**
     * Test the property 'resultDetailsConnectorTxID1'
     */
    @Test
    public void resultDetailsConnectorTxID1Test() {
        // TODO: test resultDetailsConnectorTxID1
    }

    /**
     * Test the property 'resultDetailsExtendedDescription'
     */
    @Test
    public void resultDetailsExtendedDescriptionTest() {
        // TODO: test resultDetailsExtendedDescription
    }

}
