/*
 * Payments API inbound
 * The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@peachpayments.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckoutV2Customer
 */
public class CheckoutV2CustomerTest {
    private final CheckoutV2Customer model = new CheckoutV2Customer();

    /**
     * Model tests for CheckoutV2Customer
     */
    @Test
    public void testCheckoutV2Customer() {
        // TODO: test CheckoutV2Customer
    }

    /**
     * Test the property 'merchantCustomerId'
     */
    @Test
    public void merchantCustomerIdTest() {
        // TODO: test merchantCustomerId
    }

    /**
     * Test the property 'givenName'
     */
    @Test
    public void givenNameTest() {
        // TODO: test givenName
    }

    /**
     * Test the property 'surname'
     */
    @Test
    public void surnameTest() {
        // TODO: test surname
    }

    /**
     * Test the property 'mobile'
     */
    @Test
    public void mobileTest() {
        // TODO: test mobile
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'idNumber'
     */
    @Test
    public void idNumberTest() {
        // TODO: test idNumber
    }

}
