/*
 * Payments API inbound
 * The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@peachpayments.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentGetAllPaymentLinksResponseMeta
 */
public class PaymentGetAllPaymentLinksResponseMetaTest {
    private final PaymentGetAllPaymentLinksResponseMeta model = new PaymentGetAllPaymentLinksResponseMeta();

    /**
     * Model tests for PaymentGetAllPaymentLinksResponseMeta
     */
    @Test
    public void testPaymentGetAllPaymentLinksResponseMeta() {
        // TODO: test PaymentGetAllPaymentLinksResponseMeta
    }

    /**
     * Test the property 'perPage'
     */
    @Test
    public void perPageTest() {
        // TODO: test perPage
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'nextOffset'
     */
    @Test
    public void nextOffsetTest() {
        // TODO: test nextOffset
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
