/*
 * Payments API inbound
 * The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@peachpayments.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentResponseOptions
 */
public class PaymentResponseOptionsTest {
    private final PaymentResponseOptions model = new PaymentResponseOptions();

    /**
     * Model tests for PaymentResponseOptions
     */
    @Test
    public void testPaymentResponseOptions() {
        // TODO: test PaymentResponseOptions
    }

    /**
     * Test the property 'sendEmail'
     */
    @Test
    public void sendEmailTest() {
        // TODO: test sendEmail
    }

    /**
     * Test the property 'sendSms'
     */
    @Test
    public void sendSmsTest() {
        // TODO: test sendSms
    }

    /**
     * Test the property 'sendWhatsapp'
     */
    @Test
    public void sendWhatsappTest() {
        // TODO: test sendWhatsapp
    }

    /**
     * Test the property 'emailCc'
     */
    @Test
    public void emailCcTest() {
        // TODO: test emailCc
    }

    /**
     * Test the property 'emailBcc'
     */
    @Test
    public void emailBccTest() {
        // TODO: test emailBcc
    }

    /**
     * Test the property 'notificationUrl'
     */
    @Test
    public void notificationUrlTest() {
        // TODO: test notificationUrl
    }

}
