/*
 * Payments API inbound
 * The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@peachpayments.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CartCartItemsInner
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CartCartItemsInner {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_MERCHANT_ITEM_ID = "merchantItemId";
  @SerializedName(SERIALIZED_NAME_MERCHANT_ITEM_ID)
  private String merchantItemId;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private Integer quantity;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private String price;

  public static final String SERIALIZED_NAME_WEIGHT_IN_KG = "weightInKg";
  @SerializedName(SERIALIZED_NAME_WEIGHT_IN_KG)
  private Double weightInKg;

  public static final String SERIALIZED_NAME_CATEGORY = "category";
  @SerializedName(SERIALIZED_NAME_CATEGORY)
  private String category;

  public CartCartItemsInner() {
  }

  public CartCartItemsInner description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * The description of the item in the shopping cart.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Gaming laptop", value = "The description of the item in the shopping cart.")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public CartCartItemsInner name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * The name of the item in the shopping cart.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Laptop", value = "The name of the item in the shopping cart.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public CartCartItemsInner merchantItemId(String merchantItemId) {
    
    
    
    
    this.merchantItemId = merchantItemId;
    return this;
  }

   /**
   * The unique identifier of the item in the shopping cart.
   * @return merchantItemId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "item123", value = "The unique identifier of the item in the shopping cart.")

  public String getMerchantItemId() {
    return merchantItemId;
  }


  public void setMerchantItemId(String merchantItemId) {
    
    
    
    this.merchantItemId = merchantItemId;
  }


  public CartCartItemsInner quantity(Integer quantity) {
    if (quantity != null && quantity < 1) {
      throw new IllegalArgumentException("Invalid value for quantity. Must be greater than or equal to 1.");
    }
    if (quantity != null && quantity > 999999) {
      throw new IllegalArgumentException("Invalid value for quantity. Must be less than or equal to 999999.");
    }
    
    
    this.quantity = quantity;
    return this;
  }

   /**
   * The number of items in the shopping cart.
   * minimum: 1
   * maximum: 999999
   * @return quantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "125", value = "The number of items in the shopping cart.")

  public Integer getQuantity() {
    return quantity;
  }


  public void setQuantity(Integer quantity) {
    if (quantity != null && quantity < 1) {
      throw new IllegalArgumentException("Invalid value for quantity. Must be greater than or equal to 1.");
    }
    if (quantity != null && quantity > 999999) {
      throw new IllegalArgumentException("Invalid value for quantity. Must be less than or equal to 999999.");
    }
    
    this.quantity = quantity;
  }


  public CartCartItemsInner price(String price) {
    
    
    
    
    this.price = price;
    return this;
  }

   /**
   * The price of the item in the shopping cart.
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "05.25", value = "The price of the item in the shopping cart.")

  public String getPrice() {
    return price;
  }


  public void setPrice(String price) {
    
    
    
    this.price = price;
  }


  public CartCartItemsInner weightInKg(Double weightInKg) {
    if (weightInKg != null && weightInKg < 0.01) {
      throw new IllegalArgumentException("Invalid value for weightInKg. Must be greater than or equal to 0.01.");
    }
    if (weightInKg != null && weightInKg > 999999.99) {
      throw new IllegalArgumentException("Invalid value for weightInKg. Must be less than or equal to 999999.99.");
    }
    
    
    this.weightInKg = weightInKg;
    return this;
  }

  public CartCartItemsInner weightInKg(Integer weightInKg) {
    if (weightInKg != null && weightInKg < 0.01) {
      throw new IllegalArgumentException("Invalid value for weightInKg. Must be greater than or equal to 0.01.");
    }
    if (weightInKg != null && weightInKg > 999999.99) {
      throw new IllegalArgumentException("Invalid value for weightInKg. Must be less than or equal to 999999.99.");
    }
    
    
    this.weightInKg = weightInKg.doubleValue();
    return this;
  }

   /**
   * The weight (in kg) of the item in the shopping cart.
   * minimum: 0.01
   * maximum: 999999.99
   * @return weightInKg
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "5.25", value = "The weight (in kg) of the item in the shopping cart.")

  public Double getWeightInKg() {
    return weightInKg;
  }


  public void setWeightInKg(Double weightInKg) {
    if (weightInKg != null && weightInKg < 0.01) {
      throw new IllegalArgumentException("Invalid value for weightInKg. Must be greater than or equal to 0.01.");
    }
    if (weightInKg != null && weightInKg > 999999.99) {
      throw new IllegalArgumentException("Invalid value for weightInKg. Must be less than or equal to 999999.99.");
    }
    
    this.weightInKg = weightInKg;
  }


  public CartCartItemsInner category(String category) {
    
    
    
    
    this.category = category;
    return this;
  }

   /**
   * The category of the item in the shopping cart.
   * @return category
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "electronics", value = "The category of the item in the shopping cart.")

  public String getCategory() {
    return category;
  }


  public void setCategory(String category) {
    
    
    
    this.category = category;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CartCartItemsInner instance itself
   */
  public CartCartItemsInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartCartItemsInner cartCartItemsInner = (CartCartItemsInner) o;
    return Objects.equals(this.description, cartCartItemsInner.description) &&
        Objects.equals(this.name, cartCartItemsInner.name) &&
        Objects.equals(this.merchantItemId, cartCartItemsInner.merchantItemId) &&
        Objects.equals(this.quantity, cartCartItemsInner.quantity) &&
        Objects.equals(this.price, cartCartItemsInner.price) &&
        Objects.equals(this.weightInKg, cartCartItemsInner.weightInKg) &&
        Objects.equals(this.category, cartCartItemsInner.category)&&
        Objects.equals(this.additionalProperties, cartCartItemsInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, name, merchantItemId, quantity, price, weightInKg, category, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartCartItemsInner {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    merchantItemId: ").append(toIndentedString(merchantItemId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    weightInKg: ").append(toIndentedString(weightInKg)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("name");
    openapiFields.add("merchantItemId");
    openapiFields.add("quantity");
    openapiFields.add("price");
    openapiFields.add("weightInKg");
    openapiFields.add("category");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CartCartItemsInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CartCartItemsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CartCartItemsInner is not found in the empty JSON string", CartCartItemsInner.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("merchantItemId") != null && !jsonObj.get("merchantItemId").isJsonNull()) && !jsonObj.get("merchantItemId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchantItemId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantItemId").toString()));
      }
      if ((jsonObj.get("price") != null && !jsonObj.get("price").isJsonNull()) && !jsonObj.get("price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("price").toString()));
      }
      if ((jsonObj.get("category") != null && !jsonObj.get("category").isJsonNull()) && !jsonObj.get("category").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `category` to be a primitive type in the JSON string but got `%s`", jsonObj.get("category").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CartCartItemsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CartCartItemsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CartCartItemsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CartCartItemsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<CartCartItemsInner>() {
           @Override
           public void write(JsonWriter out, CartCartItemsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CartCartItemsInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CartCartItemsInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CartCartItemsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CartCartItemsInner
  * @throws IOException if the JSON string is invalid with respect to CartCartItemsInner
  */
  public static CartCartItemsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CartCartItemsInner.class);
  }

 /**
  * Convert an instance of CartCartItemsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

